version: '3.8'
services:
  wathq:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - wathq-db
    networks:
      - app-network
  wathq-db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: 'wathq'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '123456789'
      MYSQL_ROOT_PASSWORD: '123456789'
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - "33063:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: 'wathq-db'
      PMA_USER: 'root'
      PMA_PASSWORD: '123456789'
    ports:
      - "8081:80"
    depends_on:
      - wathq-db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    external: true
